[package]
name = "conways_game"
version = "0.1.0"
authors = ["hman523 <shbarbella@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
colored = "1.8"
